// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJjV_c35OLcA-24TFlaDrIN1_V3ih3p4k',
    appId: '1:574043678818:web:a3ef6375253ecf4187493b',
    messagingSenderId: '574043678818',
    projectId: 'rxswiftmobileapplication-d8e74',
    authDomain: 'rxswiftmobileapplication-d8e74.firebaseapp.com',
    storageBucket: 'rxswiftmobileapplication-d8e74.firebasestorage.app',
    measurementId: 'G-E66XJ8FTCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATxwAAQP40KpZwMUv7x-jPZunVgcIRW9s',
    appId: '1:574043678818:android:5543e0e5af34165b87493b',
    messagingSenderId: '574043678818',
    projectId: 'rxswiftmobileapplication-d8e74',
    storageBucket: 'rxswiftmobileapplication-d8e74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnDxq5e-aUv-v2RWlNrgxOt8v3s_gaGKU',
    appId: '1:574043678818:ios:cffe3780a54b1aa787493b',
    messagingSenderId: '574043678818',
    projectId: 'rxswiftmobileapplication-d8e74',
    storageBucket: 'rxswiftmobileapplication-d8e74.firebasestorage.app',
    iosBundleId: 'com.rxswift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnDxq5e-aUv-v2RWlNrgxOt8v3s_gaGKU',
    appId: '1:574043678818:ios:9fa5fe80262c4b0b87493b',
    messagingSenderId: '574043678818',
    projectId: 'rxswiftmobileapplication-d8e74',
    storageBucket: 'rxswiftmobileapplication-d8e74.firebasestorage.app',
    iosBundleId: 'com.example.rxswift',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJjV_c35OLcA-24TFlaDrIN1_V3ih3p4k',
    appId: '1:574043678818:web:8ea3cab640bee45a87493b',
    messagingSenderId: '574043678818',
    projectId: 'rxswiftmobileapplication-d8e74',
    authDomain: 'rxswiftmobileapplication-d8e74.firebaseapp.com',
    storageBucket: 'rxswiftmobileapplication-d8e74.firebasestorage.app',
    measurementId: 'G-DMJXP8YW0X',
  );
}
